/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Robot walle = new Robot("Wall-e", 200, new int[] { 5, 2 }, "North", 30, 3);

        walle.loadPlanRobot("MEDMEEMDM");
    }
}
