/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String plan = new String("MEDMEEMDM");

        for (int i = plan.length(); i > 0; i--) {
            // Execute one command of the list
            plan = plan.substring(1, plan.length());
            // Show remaining commands
        }
    }

}
